name: Specs

on: pull_request_target

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}

      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.x'
          cache: 'npm'
    - run: npm ci
    - run: npm run lint
  specs:
    name: Specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}

      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.x'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install --prefer-offline --no-audit
      - name: Unit Test
        run: npm run test:unit