name: Release Package

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:unit
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}